# https://medium.com/javascript-in-plain-english/publish-update-npm-packages-with-github-actions-e4d786ffd62a
name: 'Commit tests'
on: [push]
env:
  SERVICE_NAME: nlp-transformer-models
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv package manager
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install
      # - name: Download Spacy model
        # run: python -m spacy download en
      - name: Run tests
        run: pytest
